### ISSUE TITLE
unklar - wo ist der callback?

### ISSUE THREAD

**Issue by d-koppenhagen** [hftl-ims-research/wonder#7]
https://github.com/hftl-ims-research/wonder/blob/wondergui/src/libs/Participant.js#L215

**Comment by jhamfler** [comment]
callback is calling an anonymous function (asterisk marks the position where the callback will land)
in Conversation.js

this.myParticipant.createMyself(this.myParticipant:undefined.identity, recvInvitation.body.constraints:Array[Object], this.onRTCEvt.bind(this:window):function, this.onMessage.bind(this:Window):function, function () {...*})

https://github.com/hftl-ims-research/wonder/blob/wondergui/src/libs/Conversation.js#L240-L351

errorCallback as the last parameter has been left out, because it provides no function
